### PR TITLE
Issue/troogle invocation

### PR DESCRIPTION
**Pull request by fref**

### CODE REVIEW

**Comment by Canop** [comment]
@fref did you notice The Travis build failed (because of a formatting problem) ?

**Comment by fref** [comment]
I'll check. I thought my IDE was properly configured for the chrall conventions

**Comment by fref** [comment]
Fixed (tentatively)
That being said, the code convention is not consistent, since you have spaces before if-blocks.

**Comment by Canop** [comment]
Space before braces in if, while, and other control constructs.
No space before function body.
This is perfectly consistent.

**Pull request merged**
